/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectGroupRouteImport } from './routes/select-group'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GroupRouteImport } from './routes/group'
import { Route as IndexRouteImport } from './routes/index'

const SelectGroupRoute = SelectGroupRouteImport.update({
  id: '/select-group',
  path: '/select-group',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoute = GroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/group': typeof GroupRoute
  '/join': typeof JoinRoute
  '/select-group': typeof SelectGroupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/group': typeof GroupRoute
  '/join': typeof JoinRoute
  '/select-group': typeof SelectGroupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/group': typeof GroupRoute
  '/join': typeof JoinRoute
  '/select-group': typeof SelectGroupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/group' | '/join' | '/select-group'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/group' | '/join' | '/select-group'
  id: '__root__' | '/' | '/group' | '/join' | '/select-group'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupRoute: typeof GroupRoute
  JoinRoute: typeof JoinRoute
  SelectGroupRoute: typeof SelectGroupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-group': {
      id: '/select-group'
      path: '/select-group'
      fullPath: '/select-group'
      preLoaderRoute: typeof SelectGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group': {
      id: '/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupRoute: GroupRoute,
  JoinRoute: JoinRoute,
  SelectGroupRoute: SelectGroupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
